language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

services:
  - postgresql

install:
  - npm install

before_script:
  - echo "Welcome to TODO app😁"
  - psql -c 'drop database if exists todo_test;' -U postgres
  - psql -c 'create database todo_test;' -U postgres

script:
  - npm test

after_success:
  - npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
